site_name: Agile Grasper Documentation
repo_url: https://github.com/beatrizleon/documentation

copyright: "Copyright Â© 2018 Shadow Robot Company"
theme: readthedocs

pages:

- User Documentation:
    - 'Introduction to Agile Grasper': 'setting_up_the_grasper.md'
    - 'Optoforce': 'optoforce/README.md'
