site_name: Modular Grasper Documentation
repo_url: https://github.com/shadow-robot/fh_documentation.git

copyright: "Copyright Â© 2018 Shadow Robot Company"
theme: readthedocs

pages:
- Home: index.md
- User Documentation:
    - 'Setting up the grasper': 'user_guide/2_setting_up_the_grasper.md'
    - 'Getting started': 'user_guide/3_getting_started.md'
    - 'Mechanical Description of the Grasper': 'user_guide/4_mechanical_description.md'
    - 'Maintaining the Grasper': 'user_guide/6_maintaining_grasper.md'
    - 'Peripherals': 'user_guide/7_peripherals.md'
    - 'FAQ': 'user_guide/8_FAQ.md'
